# Generated by Django 3.2.7 on 2021-10-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'So-so'), (2, 'Ok'), (3, 'Not bad'), (4, 'Good'), (5, 'Perfect')], default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
