# Generated by Django 3.2.7 on 2021-10-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0008_auto_20211027_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='body.answer'),
        ),
    ]
