# Generated by Django 3.2.7 on 2021-10-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodys', '0003_favorites_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='answer',
            new_name='answers',
        ),
    ]
