# Generated by Django 3.2.7 on 2021-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='newspic'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='urls',
            field=models.URLField(null=True),
        ),
    ]
