# Generated by Django 3.2.7 on 2021-10-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pars', '0002_auto_20211029_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='urls',
        ),
        migrations.AddField(
            model_name='news',
            name='csv',
            field=models.FileField(default='Pars/news.csv', upload_to=''),
        ),
    ]
